version: '3.9'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '9001:9001'
    env_file:
      - .env.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./api:/app
      - /app/node_modules
    command: ['npm', 'run', 'dev']
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    env_file:
      - .env.dev
    volumes:
      - db_data:/var/lib/postgresql/data

  test-api:
    build:
      context: ./api
      dockerfile: Dockerfile.test
    environment:
      - NODE_ENV=test
    env_file:
      - .env.dev
    command: ['npm', 'run', 'test']
    depends_on:
      - postgres

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    env_file:
      - .env.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/app
      - /app/node_modules
    command: ['npm', 'run', 'dev']
    depends_on:
      - api

  test-client:
    build:
      context: ./client
      dockerfile: Dockerfile.test
    environment:
      - NODE_ENV=test
    env_file:
      - .env.dev
    command: ['npm', 'run', 'test']

volumes:
  db_data:
  node_modules:
