version: '3.9'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '9001:9001'
    env_file:
      - .env.dev
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./api:/app/
      - node_modules:/app/node_modules
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    env_file:
      - .env.dev
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  node_modules:
