FROM node:20 AS build

WORKDIR /app

COPY package*.json /app/

RUN npm install

COPY . .

RUN npm run build

FROM node:20-slim

WORKDIR /app

COPY --from=build /app/dist /app/dist

COPY package*.json /app/

RUN npm install --only=production

ENV NODE_ENV=production

EXPOSE 80

CMD ["node", "./dist/app.js"]