version: '3.8'

services:
  api-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'
    environment:
      NODE_ENV: production

  api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '9001:9001'
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
